# Generated by Django 5.2.6 on 2026-04-13 17:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Código/SKU')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5.0, help_text='Umbral para alertas', max_digits=10)),
                ('ubicacion', models.CharField(help_text='Ej. Pasillo A, Estante 3', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('centro_costos', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para borrado lógico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DESPACHADO', 'Despachado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.proyecto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso por Compra'), ('SALIDA', 'Salida por Requerimiento'), ('AJUSTE', 'Ajuste de Inventario')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificado_calidad', models.FileField(blank=True, help_text='Subir solo archivos PDF', null=True, upload_to='certificados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='web.material')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requerimiento_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.requerimiento')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
        migrations.CreateModel(
            name='DetalleRequerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_despachada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.material')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='web.requerimiento')),
            ],
        ),
    ]
