# Generated by Django 6.0.1 on 2026-04-15 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_detallerequerimiento_id_alter_material_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Inventario (Materiales y Consumibles)'},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'verbose_name_plural': 'Bitácora de Movimientos (Auditoría)'},
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('MATERIAL', 'Material Estructural / Acero'), ('CONSUMIBLE', 'Consumible / Herramienta Menor')], default='MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='certificado_calidad',
            field=models.FileField(blank=True, help_text='Opcional: Certificado de calidad del lote de acero', null=True, upload_to='certificados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso por Compra (Abastecimiento)'), ('SALIDA', 'Salida por Requerimiento (Despacho)'), ('AJUSTE', 'Ajuste Manual de Inventario')], max_length=15),
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('proveedor', models.CharField(help_text='Nombre de la ferretería o distribuidor', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (Cotizando)'), ('EMITIDA', 'Emitida al Proveedor'), ('RECIBIDA', 'Recibida en Bodega (Stock Actualizado)'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('documento_respaldo', models.FileField(blank=True, help_text='Sube la factura, nota de venta o guía de remisión', null=True, upload_to='compras_facturas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.material')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='web.ordencompra')),
            ],
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='orden_compra_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.ordencompra'),
        ),
    ]
