# Generated by Django 6.0.1 on 2026-04-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas_compras/', verbose_name='Archivo Factura'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Factura'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
