# Generated by Django 6.0.1 on 2026-04-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_ordencompra_archivo_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='archivo_factura',
        ),
    ]
