# Generated by Django 6.0.1 on 2026-04-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_ordencompra_archivo_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Justificación si es un AJUSTE manual', null=True),
        ),
    ]
