# Generated by Django 6.0.1 on 2026-04-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_movimientoinventario_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Justificación detallada si es un AJUSTE manual', null=True),
        ),
    ]
