# Generated by Django 6.0.2 on 2026-04-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_movimientoinventario_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENVIADO_A_COMPRAS', 'Pendiente de Cotización (En Compras)'), ('COTIZADO', 'Cotizado (Esperando Aprobación Admin)'), ('PROCESADO', 'Procesado (Órdenes Generadas / Rechazados)')], default='ENVIADO_A_COMPRAS', max_length=30)),
                ('observaciones_admin', models.TextField(blank=True, help_text='Instrucciones del admin para compras')),
                ('requerimiento_origen', models.ForeignKey(blank=True, help_text='Ticket original del solicitante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.requerimiento')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor_cotizado', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('especificaciones_tecnicas', models.TextField(blank=True, help_text='Norma del acero, espesores reales, etc.')),
                ('certificado_calidad_incluido', models.BooleanField(default=False, help_text='¿El proveedor entrega certificado de calidad (Ej. INEN, ASTM)?')),
                ('archivo_cotizacion', models.FileField(blank=True, null=True, upload_to='cotizaciones/%Y/%m/')),
                ('estado_aprobacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado para Compra'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Si se rechaza, explicar al solicitante por qué (Ej. Muy caro, cambiar diseño)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.material')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_cotizados', to='web.solicitudcompra')),
            ],
        ),
    ]
